services:
  # The postgreSQL database
  db:
  # Using the latest PostGreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: speenum1!

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
